### ISSUE TITLE
Incompatibility with "Fill the blanks - Multiple type:cloze support

### ISSUE THREAD

**Issue by unit-of-inductance** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#4]
From a comment on the [Add-Ons page on ankiweb.net](https://ankiweb.net/shared/info/711285688). Have not confirmed this myself.

**Comment by unit-of-inductance** [comment]
Fixing the incompatibilities with other Add-Ons changing the way answering works would probably require a (cleaner) rewrite of the Add-On on my part. I'm not opposed to doing that, but don't quite have the time currently.

I have asked a question in the user forums whether supporting multiple type fields might be something which could be added to Anki itself (i.e. if the changes this Add-On makes could be incorporated into the original code). If that pans out, a rewrite would probably not be necessary.

In any way, I think I'm going to wait for their answer before deciding how to proceed.

Still, if anyone has a Pull Request with a fix, I'd gladly take it!

**Comment by EugeneTarasenko** [comment]
I am experiencing the same issue. It shows an error message when trying to use these two addons at the same time:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the [add-ons section](https://forums.ankiweb.net/c/add-ons/11) of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.14.1 PyQt 5.14.1
Platform: Mac 12.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-12-06 21:13:46
Add-ons possibly involved: ⁨Multiple type fields on card for 21, Image Occlusion Enhanced, No Space Dash Prevents you from seeing answers without reading a question, Fill the blanks - Multiple typecloze support⁩
Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/Users/eugen/Library/Application Support/Anki2/addons21/1933645497/handler.py", line 256, in _onFillBlankAnswer
    reviewer._showAnswer()
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/Users/eugen/Library/Application Support/Anki2/addons21/1409134430/__init__.py", line 39, in noEasy
    return _old(self)
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/Users/eugen/Library/Application Support/Anki2/addons21/1374772155/main.py", line 278, in on_show_answer
    return _old(self)
  File "aqt.reviewer", line 402, in _showAnswer
  File "aqt.reviewer", line 332, in _mungeQA
  File "/Users/eugen/Library/Application Support/Anki2/addons21/711285688/Multiple_type_fields_on_card_for_2_1.py", line 43, in myTypeAnsFilter
    return self.typeAnsAnswerFilter(buf, 0)
TypeError: typeAnsAnswerFilter() takes 2 positional arguments but 3 were given
Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/Users/eugen/Library/Application Support/Anki2/addons21/711285688/Multiple_type_fields_on_card_for_2_1.py", line 134, in myOnTypedAnswer
    self.typedAnswer = val or [""]*len(self.typeCorrect)
TypeError: object of type 'FieldsContext' has no len()
```

**Comment by unit-of-inductance** [comment]
This has apparently been solved in version 2.7 of "Fill the blanks", see https://github.com/ssricardo/anki-plugins/issues/115.

**Comment by unit-of-inductance** [comment]
Though I also got an email saying that this issue is still present, hmm... I think I'll reopen this for now
