### ISSUE TITLE
An error occurred. Multiple type fields on card for 21

### ISSUE THREAD

**Issue by raj664** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#6]
Hi,

**I’m beginner to this anki app on _desktop (Ubuntu 22.04 LTS )_ ,I tried Add on _“Multiple type fields on card for 21_” for the first time & It was showing show error msg.**

1. I tried to find the  Anki community  & google however no luck,plx let me know what to do?
2. Finally I just uninstalled it, would be suggest me the an alternative for this add on.

`[Anki Desktop](https://forums.ankiweb.net/c/anki-desktop/9)
profile, messages, bookmarks and preferences
​
Welcome! This is a place to discuss Anki, and ask any questions you may have. Before asking a question, please see [these instructions](https://faqs.ankiweb.net/getting-help.html).

[An error occurred. Please start Anki while holding down the shift:: Image occlusion enhanced ](https://forums.ankiweb.net/t/an-error-occurred-please-start-anki-while-holding-down-the-shift-image-occlusion-enhanced/22629)
[Anki Desktop](https://forums.ankiweb.net/c/anki-desktop/9)

[ankiraj369](https://forums.ankiweb.net/u/ankiraj369)
[19h](https://forums.ankiweb.net/t/an-error-occurred-please-start-anki-while-holding-down-the-shift-image-occlusion-enhanced/22629?u=ankiraj369)
Hi,

I’m beginner to this anki app on Ubuntu 22.04 LTS ,I tried Add on “Image occlusion enhanced” for the first time & It was showing show error msg.Screenshot from 2022-08-27 15-11-59.

List item
I tried this “disable add-ons and restart Anki”

List item
Bug

type or paste coDebug info:
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-08-26 15:56:34
Add-ons possibly involved: <U+2068>Multiple type fields on card for 21, Image Occlusion Enhanced<U+2069>

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "/home/xxxx69/.local/share/Anki2/addons21/711285688/Multiple_type_fields_on_card_for_2_1.py", line 135, in myOnTypedAnswer
    self._showAnswer()
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "/home/xxx369/.local/share/Anki2/addons21/1374772155/main.py", line 280, in on_show_answer
    ret = _old(self)
  File "aqt.reviewer", line 402, in _showAnswer
  File "aqt.reviewer", line 332, in _mungeQA
  File "/home/xxx369/.local/share/Anki2/addons21/711285688/Multiple_type_fields_on_card_for_2_1.py", line 43, in myTypeAnsFilter
    return self.typeAnsAnswerFilter(buf, 0)
  File "/home/xxx369/.local/share/Anki2/addons21/711285688/Multiple_type_fields_on_card_for_2_1.py", line 99, in myTypeAnsAnswerFilter
    cor = self.mw.col.media.strip(self.typeCorrect[i])
  File "anki.media", line 153, in strip
  File "re", line 210, in sub
TypeError: expected string or bytes-like object
de here`
![Screenshot from 2022-08-27 15-11-59](https://user-images.githubusercontent.com/44313300/187057307-d7108870-8cbf-4776-8906-ba17dd54ef6e.png)
![anki muti type](https://user-images.githubusercontent.com/44313300/187057324-e693ccd2-262c-4ea8-aae8-7845a97835ca.png)

**Comment by unit-of-inductance** [comment]
This seems to be an incompatibility between Image Occlusion Enhanced and Multiple type fields on card (both seem to monkey patch the Reviewer). Fixing this would probably require a rework which I'm not quite up to right now, so I probably won't fix this in the near future. Any help or PRs are welcome however.

**Comment by raj664** [comment]
What do u mean by PR??

**Comment by unit-of-inductance** [comment]
A pull request, meaning someone else contributing their own fix for this.

**Comment by unit-of-inductance** [comment]
I'm closing these incompatibility issues for now, since noone seems to be interested in helping with them. I'm happy to reopen them if someone volunteers though!
