### ISSUE TITLE
 error occurs

### ISSUE THREAD

**Issue by cindynap** [r0uv3n/Multiple-type-fields-on-Card-for-Anki-2.1#9]
After I revised the cards with multi-type, errors popped up.

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-12 22:19:42

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 253, in on_focus_changed
  File "aqt.hooks_gen", line 2766, in __call__
  File "aqt.main", line 750, in on_focus_did_change
  File "aqt.reviewer", line 174, in refresh_if_needed
  File "aqt.reviewer", line 205, in _redraw_current_card
  File "decorator", line 232, in fun
  File "anki.hooks", line 89, in decorator_wrapper
  File "anki.hooks", line 86, in repl
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\1374772155\main.py", line 278, in on_show_answer
    return _old(self)
  File "aqt.reviewer", line 402, in _showAnswer
  File "aqt.reviewer", line 332, in _mungeQA
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\711285688\Multiple_type_fields_on_card_for_2_1.py", line 43, in myTypeAnsFilter
    return self.typeAnsAnswerFilter(buf, 0)
TypeError: typeAnsAnswerFilter() takes 2 positional arguments but 3 were given

**Comment by cindynap** [comment]
I finally realized that I was doing multi-input on a cloze note. So it didn't work. Is it possible to have multi-input even on basic, close note?

**Comment by cindynap** [comment]
oops

This is the error info after I test this addon on a proper input note. It appeared when I clicked the answer button during my study of other cards.

Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 5.15.2 PyQt 5.15.5
Platform: Windows 10
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-10-13 23:10:20

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 568, in handler
  File "C:\Users\cindy\AppData\Roaming\Anki2\addons21\711285688\Multiple_type_fields_on_card_for_2_1.py", line 134, in myOnTypedAnswer
    self.typedAnswer = val or [""]*len(self.typeCorrect)
TypeError: object of type 'NoneType' has no len()

**Comment by unit-of-inductance** [comment]
Sorry for the late reply, could you maybe send the Card Template you used for this? Do you have any other AddOns installed? On a fresh install I could not reproduce the issue.

**Comment by unit-of-inductance** [comment]
Without further info I can't really do anything here. This is probably a similar issue to others in this tracker that relate to incompatibilities with other Addons that monkey patch the same functions. It seems a rework on the side of the Anki team of the `Reviewer`  is coming, maybe that will enable us to more easily avoid incompatibilities.

For now, I'll mark this as closed. Though if you have any further info, I'd be happy to reopen the issue!
